/**
 * Creates (or recreates) a demo account with a sample collection.
 * Usage: npm run build && npm run db:seed
 */
import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PasswordService } from '../auth/password.service.js';
import { PrismaClient } from '../generated/prisma/client.js';
import type { SaveGameDto } from '../games/dto/save-game.dto.js';
import { toGameData } from '../games/games.query.js';

const DEMO_EMAIL = 'demo@example.com';
const DEMO_PASSWORD = 'demo-collector';

const games: SaveGameDto[] = [
  {
    title: 'The Legend of Zelda: Ocarina of Time',
    platform: 'N64',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Action-adventure',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    releaseYear: 1998,
    productCode: 'NUS-NZLP-EUR',
    purchasePrice: 1290,
    purchaseDate: '2023-04-12',
    purchasePlace: 'Flea market',
    estimatedValue: 2400,
    storageLocation: 'Shelf A',
    rating: 10,
    favorite: true,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Super Mario 64',
    platform: 'N64',
    region: 'PAL',
    completeness: 'LOOSE',
    condition: 'GOOD',
    genre: 'Platformer',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    releaseYear: 1996,
    purchasePrice: 650,
    purchaseDate: '2022-11-03',
    estimatedValue: 800,
    storageLocation: 'Shelf A',
    rating: 9,
    playStatus: 'COMPLETED',
  },
  {
    title: 'GoldenEye 007',
    platform: 'N64',
    region: 'PAL',
    completeness: 'GAME_AND_BOX',
    condition: 'GOOD',
    genre: 'FPS',
    developer: 'Rare',
    publisher: 'Nintendo',
    releaseYear: 1997,
    purchasePrice: 900,
    estimatedValue: 1100,
    storageLocation: 'Shelf A',
    rating: 8,
  },
  {
    title: 'Banjo-Kazooie',
    platform: 'N64',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'NEAR_MINT',
    genre: 'Platformer',
    developer: 'Rare',
    publisher: 'Nintendo',
    releaseYear: 1998,
    estimatedValue: 1500,
    storageLocation: 'Shelf A',
    rating: 9,
    favorite: true,
  },
  {
    title: 'Final Fantasy VII',
    platform: 'PS1',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'RPG',
    developer: 'Square',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 1997,
    productCode: 'SCES-00867',
    purchasePrice: 800,
    purchaseDate: '2021-06-20',
    estimatedValue: 1200,
    storageLocation: 'Shelf B',
    rating: 10,
    favorite: true,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Metal Gear Solid',
    platform: 'PS1',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Stealth',
    developer: 'Konami',
    publisher: 'Konami',
    releaseYear: 1998,
    productCode: 'SLES-01370',
    purchasePrice: 450,
    estimatedValue: 700,
    storageLocation: 'Shelf B',
    rating: 10,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Crash Bandicoot',
    platform: 'PS1',
    region: 'PAL',
    completeness: 'GAME_AND_MANUAL',
    condition: 'FAIR',
    genre: 'Platformer',
    developer: 'Naughty Dog',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 1996,
    purchasePrice: 250,
    estimatedValue: 400,
    storageLocation: 'Shelf B',
    rating: 8,
  },
  {
    title: 'Gran Turismo 3: A-Spec',
    platform: 'PS2',
    region: 'PAL',
    edition: 'Platinum',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Racing',
    developer: 'Polyphony Digital',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 2001,
    productCode: 'SCES-50294',
    purchasePrice: 150,
    estimatedValue: 200,
    storageLocation: 'Shelf B',
    rating: 8,
  },
  {
    title: 'Shadow of the Colossus',
    platform: 'PS2',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'NEAR_MINT',
    genre: 'Action-adventure',
    developer: 'Team Ico',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 2005,
    purchasePrice: 600,
    estimatedValue: 900,
    storageLocation: 'Shelf B',
    rating: 10,
    favorite: true,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Grand Theft Auto: San Andreas',
    platform: 'PS2',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Action',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    releaseYear: 2004,
    purchasePrice: 200,
    estimatedValue: 300,
    storageLocation: 'Shelf B',
    rating: 9,
  },
  {
    title: 'Silent Hill 2',
    platform: 'PS2',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Survival horror',
    developer: 'Konami',
    publisher: 'Konami',
    releaseYear: 2001,
    estimatedValue: 2200,
    storageLocation: 'Shelf B',
    rating: 10,
    playStatus: 'PLAYING',
  },
  {
    title: 'The Last of Us',
    platform: 'PS3',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'MINT',
    genre: 'Action-adventure',
    developer: 'Naughty Dog',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 2013,
    purchasePrice: 300,
    estimatedValue: 250,
    storageLocation: 'Shelf C',
    rating: 10,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Bloodborne',
    platform: 'PS4',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'MINT',
    genre: 'Action RPG',
    developer: 'FromSoftware',
    publisher: 'Sony Computer Entertainment',
    releaseYear: 2015,
    purchasePrice: 399,
    estimatedValue: 350,
    storageLocation: 'Shelf C',
    rating: 10,
    favorite: true,
    playStatus: 'ABANDONED',
  },
  {
    title: 'Elden Ring',
    platform: 'PS5',
    region: 'PAL',
    edition: 'Launch Edition',
    completeness: 'CIB',
    condition: 'MINT',
    genre: 'Action RPG',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseYear: 2022,
    barcode: '3391892017625',
    purchasePrice: 1599,
    purchaseDate: '2022-02-25',
    purchasePlace: 'Online store',
    estimatedValue: 900,
    storageLocation: 'Shelf C',
    rating: 10,
    playStatus: 'PLAYING',
  },
  {
    title: 'Astro Bot',
    platform: 'PS5',
    format: 'DIGITAL',
    genre: 'Platformer',
    developer: 'Team Asobi',
    publisher: 'Sony Interactive Entertainment',
    releaseYear: 2024,
    purchasePrice: 1499,
    purchaseDate: '2024-09-06',
    purchasePlace: 'PlayStation Store',
    rating: 9,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Halo: Combat Evolved',
    platform: 'XBOX',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'FPS',
    developer: 'Bungie',
    publisher: 'Microsoft',
    releaseYear: 2001,
    purchasePrice: 150,
    estimatedValue: 250,
    storageLocation: 'Shelf C',
    rating: 9,
  },
  {
    title: 'Fable',
    platform: 'XBOX',
    region: 'PAL',
    completeness: 'GAME_AND_BOX',
    condition: 'FAIR',
    genre: 'RPG',
    developer: 'Lionhead Studios',
    publisher: 'Microsoft',
    releaseYear: 2004,
    purchasePrice: 100,
    estimatedValue: 150,
    storageLocation: 'Shelf C',
    rating: 8,
  },
  {
    title: 'Gears of War',
    platform: 'XBOX_360',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Third-person shooter',
    developer: 'Epic Games',
    publisher: 'Microsoft',
    releaseYear: 2006,
    purchasePrice: 120,
    estimatedValue: 150,
    storageLocation: 'Shelf C',
    rating: 8,
  },
  {
    title: 'Super Mario World',
    platform: 'SNES',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Platformer',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    releaseYear: 1990,
    purchasePrice: 1800,
    estimatedValue: 2200,
    storageLocation: 'Display cabinet',
    rating: 10,
    favorite: true,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Chrono Trigger',
    platform: 'SNES',
    region: 'NTSC_U',
    completeness: 'LOOSE',
    condition: 'GOOD',
    genre: 'RPG',
    developer: 'Square',
    publisher: 'Square',
    releaseYear: 1995,
    purchasePrice: 3200,
    estimatedValue: 4000,
    storageLocation: 'Display cabinet',
    rating: 10,
  },
  {
    title: 'EarthBound',
    platform: 'SNES',
    region: 'NTSC_U',
    status: 'WISHLIST',
    genre: 'RPG',
    developer: 'Ape',
    publisher: 'Nintendo',
    releaseYear: 1995,
    estimatedValue: 9000,
    notes: 'Only complete in box, including the player’s guide.',
  },
  {
    title: 'Super Mario Bros. 3',
    platform: 'NES',
    region: 'PAL',
    completeness: 'LOOSE',
    condition: 'FAIR',
    genre: 'Platformer',
    publisher: 'Nintendo',
    releaseYear: 1988,
    purchasePrice: 700,
    estimatedValue: 900,
    storageLocation: 'Display cabinet',
    rating: 9,
  },
  {
    title: 'Pokémon Red',
    platform: 'GAME_BOY',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'RPG',
    developer: 'Game Freak',
    publisher: 'Nintendo',
    releaseYear: 1996,
    purchasePrice: 1500,
    estimatedValue: 2500,
    storageLocation: 'Display cabinet',
    rating: 9,
    favorite: true,
  },
  {
    title: 'The Legend of Zelda: Link’s Awakening DX',
    platform: 'GAME_BOY_COLOR',
    region: 'PAL',
    completeness: 'LOOSE',
    condition: 'GOOD',
    genre: 'Action-adventure',
    publisher: 'Nintendo',
    releaseYear: 1998,
    purchasePrice: 600,
    estimatedValue: 700,
    storageLocation: 'Display cabinet',
    rating: 9,
  },
  {
    title: 'Metroid Fusion',
    platform: 'GAME_BOY_ADVANCE',
    region: 'PAL',
    status: 'LENT',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Metroidvania',
    publisher: 'Nintendo',
    releaseYear: 2002,
    estimatedValue: 1200,
    rating: 9,
    notes: 'Lent to John.',
  },
  {
    title: 'Super Smash Bros. Melee',
    platform: 'GAMECUBE',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Fighting',
    developer: 'HAL Laboratory',
    publisher: 'Nintendo',
    releaseYear: 2001,
    purchasePrice: 900,
    estimatedValue: 1300,
    storageLocation: 'Shelf A',
    rating: 9,
  },
  {
    title: 'Metroid Prime',
    platform: 'GAMECUBE',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'NEAR_MINT',
    genre: 'Action-adventure',
    developer: 'Retro Studios',
    publisher: 'Nintendo',
    releaseYear: 2002,
    purchasePrice: 700,
    estimatedValue: 900,
    storageLocation: 'Shelf A',
    rating: 10,
  },
  {
    title: 'Wii Sports',
    platform: 'WII',
    region: 'PAL',
    completeness: 'LOOSE',
    condition: 'GOOD',
    genre: 'Sports',
    publisher: 'Nintendo',
    releaseYear: 2006,
    purchasePrice: 50,
    estimatedValue: 50,
    storageLocation: 'Storage box 1',
    rating: 6,
    status: 'FOR_SALE',
  },
  {
    title: 'The Legend of Zelda: Breath of the Wild',
    platform: 'SWITCH',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'MINT',
    genre: 'Action-adventure',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    releaseYear: 2017,
    purchasePrice: 1399,
    estimatedValue: 1000,
    storageLocation: 'Shelf A',
    rating: 10,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Mario Kart World',
    platform: 'SWITCH_2',
    status: 'PREORDERED',
    genre: 'Racing',
    publisher: 'Nintendo',
    releaseYear: 2025,
    purchasePrice: 1999,
  },
  {
    title: 'Sonic the Hedgehog',
    platform: 'MEGA_DRIVE',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Platformer',
    developer: 'Sonic Team',
    publisher: 'Sega',
    releaseYear: 1991,
    purchasePrice: 400,
    estimatedValue: 500,
    storageLocation: 'Display cabinet',
    rating: 8,
  },
  {
    title: 'Shenmue',
    platform: 'DREAMCAST',
    region: 'PAL',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Action-adventure',
    developer: 'Sega AM2',
    publisher: 'Sega',
    releaseYear: 2000,
    purchasePrice: 1100,
    estimatedValue: 1500,
    storageLocation: 'Display cabinet',
    rating: 9,
  },
  {
    title: 'Panzer Dragoon Saga',
    platform: 'SATURN',
    region: 'PAL',
    status: 'WISHLIST',
    genre: 'RPG',
    publisher: 'Sega',
    releaseYear: 1998,
    estimatedValue: 25000,
  },
  {
    title: 'Doom',
    platform: 'PC',
    edition: 'Big box',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'FPS',
    developer: 'id Software',
    publisher: 'id Software',
    releaseYear: 1993,
    purchasePrice: 2500,
    estimatedValue: 3500,
    storageLocation: 'Shelf D',
    rating: 10,
    favorite: true,
  },
  {
    title: 'Mafia: The City of Lost Heaven',
    platform: 'PC',
    completeness: 'CIB',
    condition: 'VERY_GOOD',
    genre: 'Action',
    developer: 'Illusion Softworks',
    publisher: 'Gathering',
    releaseYear: 2002,
    purchasePrice: 300,
    estimatedValue: 600,
    storageLocation: 'Shelf D',
    rating: 10,
    favorite: true,
    playStatus: 'COMPLETED',
  },
  {
    title: 'Vietcong',
    platform: 'PC',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'FPS',
    developer: 'Pterodon',
    publisher: 'Gathering',
    releaseYear: 2003,
    purchasePrice: 150,
    estimatedValue: 300,
    storageLocation: 'Shelf D',
    rating: 8,
  },
  {
    title: 'Kingdom Come: Deliverance',
    platform: 'PC',
    edition: 'Collector’s Edition',
    completeness: 'SEALED',
    condition: 'MINT',
    genre: 'RPG',
    developer: 'Warhorse Studios',
    publisher: 'Deep Silver',
    releaseYear: 2018,
    purchasePrice: 3500,
    estimatedValue: 4500,
    storageLocation: 'Shelf D',
    rating: 9,
  },
  {
    title: 'Dizzy: Prince of the Yolkfolk',
    platform: 'ZX_SPECTRUM',
    format: 'PHYSICAL',
    completeness: 'GAME_AND_BOX',
    condition: 'FAIR',
    genre: 'Adventure',
    publisher: 'Codemasters',
    releaseYear: 1991,
    purchasePrice: 200,
    estimatedValue: 350,
    storageLocation: 'Storage box 2',
    rating: 8,
    notes: 'Original cassette release.',
  },
  {
    title: 'Manic Miner',
    platform: 'ZX_SPECTRUM',
    status: 'WISHLIST',
    genre: 'Platformer',
    publisher: 'Bug-Byte',
    releaseYear: 1983,
  },
  {
    title: 'Turrican II: The Final Fight',
    platform: 'AMIGA',
    completeness: 'CIB',
    condition: 'GOOD',
    genre: 'Run and gun',
    developer: 'Factor 5',
    publisher: 'Rainbow Arts',
    releaseYear: 1991,
    purchasePrice: 900,
    estimatedValue: 1200,
    storageLocation: 'Storage box 2',
    rating: 9,
  },
  {
    title: 'The Secret of Monkey Island',
    platform: 'AMIGA',
    completeness: 'GAME_AND_MANUAL',
    condition: 'GOOD',
    genre: 'Adventure',
    developer: 'Lucasfilm Games',
    publisher: 'U.S. Gold',
    releaseYear: 1991,
    purchasePrice: 700,
    estimatedValue: 1100,
    storageLocation: 'Storage box 2',
    rating: 10,
  },
  {
    title: 'Impossible Mission',
    platform: 'COMMODORE_64',
    completeness: 'LOOSE',
    condition: 'POOR',
    genre: 'Platformer',
    publisher: 'Epyx',
    releaseYear: 1984,
    purchasePrice: 100,
    estimatedValue: 150,
    storageLocation: 'Storage box 2',
    rating: 7,
    status: 'SOLD',
  },
];

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
});

try {
  await prisma.user.deleteMany({ where: { email: DEMO_EMAIL } });
  const user = await prisma.user.create({
    data: {
      email: DEMO_EMAIL,
      displayName: 'Demo Collector',
      passwordHash: await new PasswordService().hash(DEMO_PASSWORD),
    },
  });
  await prisma.game.createMany({
    data: games.map((game) => ({ ...toGameData(game), userId: user.id })),
  });
  console.log(
    `Seeded ${games.length} games for ${DEMO_EMAIL} / ${DEMO_PASSWORD}`,
  );
} finally {
  await prisma.$disconnect();
}
